SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME LIKE 'Milk'
)
AND CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME LIKE 'Yogurt'
)
ORDER BY CART_ID;