WITH RECURSIVE GENERATION AS (
    # 1세대 대장균 찾기
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 다음 세대 대장균 찾기
    SELECT E.ID, E.PARENT_ID, G.GEN+1 AS GEN
    FROM ECOLI_DATA E
    INNER JOIN GENERATION G ON E.PARENT_ID = G.ID
)

SELECT ID
FROM GENERATION
WHERE GEN = 3
ORDER BY ID;