SELECT P.PRODUCT_CODE, PRICE*SALES_AMOUNT AS SALES
FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
     FROM OFFLINE_SALE
     GROUP BY PRODUCT_ID) O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;
