# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.TOTAL_SALES
# FROM FOOD_PRODUCT P
# INNER JOIN (
#     SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_SALES 
#     FROM FOOD_ORDER
#     WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE <= '2022-05-31'
#     GROUP BY PRODUCT_ID
# ) O ON P.PRODUCT_ID = O.PRODUCT_ID
# ORDER BY O.TOTAL_SALES DESC, P.PRODUCT_ID ASC;

SELECT * FROM FOOD_ORDER;