SELECT F.FLAVOR
FROM FIRST_HALF F
INNER JOIN (SELECT FLAVOR, sum(TOTAL_ORDER) AS TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR) J
        ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER+J.TOTAL_ORDER DESC
LIMIT 3;