-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER U
LEFT JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
           FROM USED_GOODS_BOARD
          WHERE STATUS LIKE "DONE"
          GROUP BY WRITER_ID) B ON B.WRITER_ID = U.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;