SELECT B.CATEGORY, SUM(S.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B
JOIN
(SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE>='2022-01-01' AND SALES_DATE<='2022-01-31'
GROUP BY BOOK_ID) S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;