SELECT P.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN 
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) M
ON P.CATEGORY = M.CATEGORY
WHERE MAX_PRICE = P.PRICE
ORDER BY MAX_PRICE DESC;

# SELECT * FROM FOOD_PRODUCT;

